import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import axios from 'axios';
import Link from 'next/link';

interface Question {
  text: string;
  difficulty: 'Easy' | 'Moderate' | 'Challenging';
  marks: number;
}

interface Section {
  title: string;
  instruction: string;
  questions: Question[];
}

interface QuestionPaper {
  _id: string;
  subject: string;
  className: string;
  timeAllowed: number;
  maxMarks: number;
  sections: Section[];
  answerKey?: string;
}

interface Assignment {
  _id: string;
  title: string;
  status: string;
  generatedPaperId?: string;
}

export default function AssignmentOutput() {
  const router = useRouter();
  const { id } = router.query;
  
  const [assignment, setAssignment] = useState<Assignment | null>(null);
  const [questionPaper, setQuestionPaper] = useState<QuestionPaper | null>(null);
  const [loading, setLoading] = useState(true);
  const [studentInfo, setStudentInfo] = useState({
    name: '',
    rollNumber: '',
    section: '',
  });

  useEffect(() => {
    if (id) {
      fetchAssignment();
    }
  }, [id]);

 const fetchAssignment = async () => {
  try {
    // Make sure id is a string
    const assignmentId = Array.isArray(id) ? id[0] : id;
    console.log('Fetching assignment with ID:', assignmentId);
    
    const response = await axios.get(`/api/assignments/${assignmentId}`);
    if (response.data.success) {
      const assignmentData = response.data.data;
      console.log('Assignment data:', assignmentData);
      setAssignment(assignmentData);
      
      // Check if generatedPaperId exists and is a string
      if (assignmentData.generatedPaperId) {
        const paperId = typeof assignmentData.generatedPaperId === 'object' 
          ? assignmentData.generatedPaperId._id || assignmentData.generatedPaperId.toString()
          : assignmentData.generatedPaperId;
        console.log('Fetching paper with ID:', paperId);
        await fetchQuestionPaper(paperId);
      } else {
        console.log('No generatedPaperId found');
        setLoading(false);
      }
    }
  } catch (error) {
    console.error('Failed to fetch assignment:', error);
    setLoading(false);
  }
};

const fetchQuestionPaper = async (paperId: string) => {
  try {
    console.log('Fetching question paper:', paperId);
    const response = await axios.get(`/api/question-papers/${paperId}`);
    if (response.data.success) {
      console.log('Question paper data:', response.data.data);
      setQuestionPaper(response.data.data);
    }
    setLoading(false);
  } catch (error) {
    console.error('Failed to fetch question paper:', error);
    setLoading(false);
  }
};

  const getDifficultyColor = (difficulty: string) => {
    switch (difficulty) {
      case 'Easy': return 'bg-green-100 text-green-800';
      case 'Moderate': return 'bg-yellow-100 text-yellow-800';
      case 'Challenging': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-lg">Loading...</div>
      </div>
    );
  }

  if (!assignment || assignment.status !== 'completed' || !questionPaper) {
    return (
      <div className="min-h-screen bg-gray-50">
        <div className="max-w-4xl mx-auto px-4 py-8">
          <Link href="/" className="text-indigo-600 hover:text-indigo-800">
            ← Back to Dashboard
          </Link>
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6 mt-8 text-center">
            <h2 className="text-xl font-semibold text-yellow-800 mb-2">Assignment Still Generating</h2>
            <p className="text-yellow-700">
              Your question paper is being generated by AI. This may take a few seconds.
              <br />
              <span className="text-sm">Status: {assignment?.status || 'Processing'}</span>
            </p>
            <button
              onClick={() => window.location.reload()}
              className="mt-4 px-4 py-2 bg-yellow-600 text-white rounded-lg hover:bg-yellow-700"
            >
              Refresh
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4">
        {/* Header */}
        <div className="mb-6">
          <Link href="/" className="text-indigo-600 hover:text-indigo-800">
            ← Back to Dashboard
          </Link>
        </div>

        {/* Question Paper */}
        <div className="bg-white rounded-lg shadow-lg overflow-hidden">
          {/* School Header */}
          <div className="border-b border-gray-200 p-6 text-center bg-gray-50">
            <h1 className="text-2xl font-bold text-gray-900">Delhi Public School, Sector-4, Bokaro</h1>
            <div className="mt-4 flex justify-between items-center">
              <div className="text-left">
                <p><strong>Subject:</strong> {questionPaper.subject}</p>
                <p><strong>Class:</strong> {questionPaper.className}</p>
              </div>
              <div className="text-right">
                <p><strong>Time Allowed:</strong> {questionPaper.timeAllowed} minutes</p>
                <p><strong>Maximum Marks:</strong> {questionPaper.maxMarks}</p>
              </div>
            </div>
          </div>

          {/* Instructions */}
          <div className="bg-yellow-50 border-b border-yellow-200 p-4">
            <p className="text-sm text-yellow-800">
              All questions are compulsory unless stated otherwise.
            </p>
          </div>

          {/* Student Info Section */}
          <div className="p-6 border-b border-gray-200">
            <div className="grid grid-cols-3 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700">Name:</label>
                <input
                  type="text"
                  value={studentInfo.name}
                  onChange={(e) => setStudentInfo({ ...studentInfo, name: e.target.value })}
                  className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md"
                  placeholder="Enter your name"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Roll Number:</label>
                <input
                  type="text"
                  value={studentInfo.rollNumber}
                  onChange={(e) => setStudentInfo({ ...studentInfo, rollNumber: e.target.value })}
                  className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md"
                  placeholder="Enter roll number"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Section:</label>
                <input
                  type="text"
                  value={studentInfo.section}
                  onChange={(e) => setStudentInfo({ ...studentInfo, section: e.target.value })}
                  className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md"
                  placeholder="Enter section"
                />
              </div>
            </div>
          </div>

          {/* Questions Sections */}
          <div className="p-6">
            {questionPaper.sections.map((section, sectionIdx) => (
              <div key={sectionIdx} className="mb-8">
                <h2 className="text-xl font-bold text-gray-900 mb-2">{section.title}</h2>
                <p className="text-sm text-gray-600 mb-4 italic">{section.instruction}</p>
                
                <div className="space-y-4">
                  {section.questions.map((question, qIdx) => (
                    <div key={qIdx} className="border border-gray-200 rounded-lg p-4">
                      <div className="flex justify-between items-start">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-2">
                            <span className="font-medium text-gray-900">
                              {qIdx + 1}.
                            </span>
                            <span className="text-gray-700">{question.text}</span>
                          </div>
                        </div>
                        <div className="flex items-center gap-2 ml-4">
                          <span className={`text-xs px-2 py-1 rounded-full ${getDifficultyColor(question.difficulty)}`}>
                            {question.difficulty}
                          </span>
                          <span className="text-sm font-medium text-gray-600">
                            [{question.marks} Marks]
                          </span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          {/* End of Paper */}
          <div className="border-t border-gray-200 p-6 text-center text-gray-500">
            <p>*** End of Question Paper ***</p>
          </div>
        </div>

        {/* Answer Key (Optional) */}
        {questionPaper.answerKey && (
          <div className="mt-6 bg-white rounded-lg shadow-lg overflow-hidden">
            <div className="bg-gray-50 border-b border-gray-200 p-4">
              <h2 className="text-lg font-semibold text-gray-900">Answer Key</h2>
            </div>
            <div className="p-6">
              <pre className="whitespace-pre-wrap text-sm text-gray-700">
                {questionPaper.answerKey}
              </pre>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}